import { RegionMapping } from "./modules/region";

/**
 * Detailed error record for a heading hierarchy violation.
 *
 * @description Emitted when a heading level skips (e.g. H1 -> H3) or uses an invalid level (H7+).
 * @see WCAG 2.1 SC 1.3.1 Info and Relationships
 */
export type HeadingOrderError = {
  /** Selector-style path to the node (e.g., "main[0] > section[1]") */
  path: string;
  /** HTML tag name of the region node */
  tagName: string;
  /** Raw heading tag or level descriptor */
  heading: string;
  /** Visible text content inside the heading element */
  text?: string;
  /** Optional reference to live DOM node */
  element?: unknown;
  /** Parsed numerical level (e.g., 4 for "h4") */
  actualLevel: number;
  /** Maximum allowed level at this context */
  expectedMaxLevel: number;
  /** Human-readable error description */
  message: string;
};

/**
 * Comprehensive audit report generated by `checkHeadingOrderReport`.
 *
 * @description Summary report object containing validity boolean and detailed error list.
 */
export type HeadingOrderReport = {
  /** Whether the audited heading hierarchy strictly complies with WCAG 2.1 SC 1.3.1 */
  isValid: boolean;
  /** List of heading hierarchy error details */
  errors: HeadingOrderError[];
};

export type ProcessHeadingLevelParams = {
  level: number;
  region: RegionMapping;
  path: string;
  errors: HeadingOrderError[];
};
