/**
 * Metadata descriptor for an individual heading element discovered in the DOM.
 *
 * @description Captures level, accessible text content, and DOM element handle.
 */
export type HeadingDetail = {
  /** Tag string (e.g. "h2") or explicit numerical level (e.g. 2) */
  level: string | number;
  /** Visible inner text of the heading element (e.g. "Pricing Plans") */
  text?: string;
  /** Optional reference to the underlying DOM node or custom element context */
  element?: unknown;
};

/**
 * Tree representation of an HTML5 landmark sectioning element or ARIA region.
 *
 * @description Data structure emitted by `drawRegion` representing sectioning tree depth.
 * @a11y Maps HTML sectioning landmarks (main, section, article) and ARIA roles for hierarchy checking.
 */
export type RegionMapping = {
  /** Identifier of the region node (e.g. "main", "section", or "div[role=\"navigation\"]") */
  tagName: string;
  /** Legacy string-only headings array (e.g. ["h1", "h2"]) */
  headings: string[];
  /** Rich heading metadata with inner text and DOM element references */
  detailedHeadings?: HeadingDetail[];
  /** Direct nested landmark child regions */
  children: RegionMapping[];
};

/**
 * Detailed error record for a heading hierarchy violation.
 *
 * @description Emitted when a heading level skips (e.g. H1 -> H3) or uses an invalid level (H7+).
 * @see WCAG 2.1 SC 1.3.1 Info and Relationships
 */
export type HeadingOrderError = {
  /** Selector-style path to the node (e.g., "main[0] > section[1]") */
  path: string;
  /** HTML tag name of the region node */
  tagName: string;
  /** Raw heading tag or level descriptor */
  heading: string;
  /** Visible text content inside the heading element */
  text?: string;
  /** Optional reference to live DOM node */
  element?: unknown;
  /** Parsed numerical level (e.g., 4 for "h4") */
  actualLevel: number;
  /** Maximum allowed level at this context */
  expectedMaxLevel: number;
  /** Human-readable error description */
  message: string;
};

/**
 * Comprehensive audit report generated by `checkHeadingOrderReport`.
 *
 * @description Summary report object containing validity boolean and detailed error list.
 */
export type HeadingOrderReport = {
  /** Whether the audited heading hierarchy strictly complies with WCAG 2.1 SC 1.3.1 */
  isValid: boolean;
  /** List of heading hierarchy error details */
  errors: HeadingOrderError[];
};
